
title: KI generierte Kurzgeshichten
description: Hier findest du eine langsam wachsende Liste von Kurzgeschichten, die automatisch mit KI generiert wurden. Die KI basiert aktuell auf mehreren Agenten, die jeweils für eigene Aspekte bei der Generierung zuständig sind. Es ist ein fortlaufendes Projekt...
